// @generated by @nkzw/fate/vite
import type { Comment, fate as fateServer, Post, User } from '../../api/src/fate.ts';
import { clientRoot, createClient, createHTTPTransport, mutation, type InferFateAPI } from 'react-fate';


type FateAPI = InferFateAPI<typeof fateServer>;

const mutations = {
  'addComment': mutation<
    Comment,
    FateAPI['mutations']['addComment']['input'],
    FateAPI['mutations']['addComment']['output']
  >('Comment'),
  'createPost': mutation<
    Post,
    FateAPI['mutations']['createPost']['input'],
    FateAPI['mutations']['createPost']['output']
  >('Post'),
  'deleteComment': mutation<
    Comment,
    FateAPI['mutations']['deleteComment']['input'],
    FateAPI['mutations']['deleteComment']['output']
  >('Comment'),
  'deletePost': mutation<
    Post,
    FateAPI['mutations']['deletePost']['input'],
    FateAPI['mutations']['deletePost']['output']
  >('Post'),
  'likePost': mutation<
    Post,
    FateAPI['mutations']['likePost']['input'],
    FateAPI['mutations']['likePost']['output']
  >('Post'),
} as const;

const roots = {
  'comment': clientRoot<Array<Comment>, 'Comment'>('Comment'),
  'post': clientRoot<Array<Post>, 'Post'>('Post'),
  'posts': clientRoot<FateAPI['lists']['posts']['output'], 'Post'>('Post'),
  'user': clientRoot<Array<User>, 'User'>('User'),
} as const;

export type GeneratedClientMutations = typeof mutations;
export type GeneratedClientRoots = typeof roots;

export const createFateClient = (options: {
  fetch?: typeof fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
  liveRetryMs?: number;
  liveUrl?: string | URL;
  onLiveError?: (error: unknown) => void;
  url: string | URL;
}) =>
  createClient<[GeneratedClientRoots, GeneratedClientMutations]>({
    mutations,
    onLiveError: options.onLiveError,
    roots,
    transport: createHTTPTransport<FateAPI>({
      fetch: options.fetch,
      headers: options.headers,
      live: true,
      liveRetryMs: options.liveRetryMs,
      liveUrl: options.liveUrl,
      url: options.url,
    }),
    types: [
        {
          type: 'User',
        },
        {
          fields: {
            author: { type: 'User' },
          },
          type: 'Comment',
        },
        {
          fields: {
            author: { type: 'User' },
            comments: { listOf: 'Comment' },
          },
          type: 'Post',
        },
      ],
  });

type GeneratedCreateFateClient = typeof createFateClient;

declare module 'react-fate/client' {
  interface ClientMutations extends GeneratedClientMutations {}
  interface ClientRoots extends GeneratedClientRoots {}

  export function createFateClient(
    ...args: Parameters<GeneratedCreateFateClient>
  ): ReturnType<GeneratedCreateFateClient>;
}

